{% set data = load_setup_py_data() %}

package:
  name: hdf5matfile
  version: {{ data.get('version') }}

source:
  git_url: "../"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.7.0
    - h5py
    - numpy>=1.15.0

test:
  imports:
    - hdf5matfile
  requires:
    - pytest
  source_files:
    - src/hdf5matfile/test
  commands:
    - pytest

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
